#!/bin/bash

finish() {
  f="${1}"
  [[ -z "${f}" || -z "${CYDIA}" ]] && return
  cydia=(${CYDIA})
  [[ ${cydia[1]} -eq 1 ]] || return
  echo "finish:${f}" >&${cydia[0]}
}

killall -9 MobileSafari profiled sharingd

finish return
